apiVersion: batch/v1
kind: Job
metadata:
  name: beegfs-rrc16p16
spec:
  backoffLimit: 6
  completions: 16
  parallelism: 16
  template:
    metadata:
      name: fio-pod
    spec:
      containers:
      - args:
        - /fio_jobfiles/run_fio.sh
        command:
        - /bin/sh
        env:
        - name: NUM_JOBS
          value: "4"
        - name: JOB_NAME
          value: "beegfs-rrc16p16"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: docker.io/brtknr/fio:v3.11.11
        #imagePullPolicy: Always
        name: fio-test
        resources: {}
        volumeMounts:
        - mountPath: /data
          subPath: bharat
          name: beegfs-pv
      hostNetwork: true
      restartPolicy: OnFailure
      volumes:
      - name: beegfs-pv
        persistentVolumeClaim:
          claimName: beegfs-pvc
