apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  labels:
    job-name: fio
  name: fio
  namespace: default
  selfLink: /apis/batch/v1/namespaces/default/jobs/fio
spec:
  backoffLimit: 6
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels:
        job-name: fio
      name: fio-pod
    spec:
      containers:
      - args:
        - /fio_jobfiles/run_fio.sh
        command:
        - /bin/sh
        env:
        - name: NUM_JOBS
          value: "8"
        - name: JOB_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: docker.io/brtknr/fio:v3.11
        imagePullPolicy: Always
        name: fio-test
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: fio-pv-volume
      hostNetwork: true
      restartPolicy: OnFailure
      volumes:
      - name: fio-pv-volume
        persistentVolumeClaim:
          claimName: fio-pv-claim
