kind: Job
apiVersion: batch/v1
metadata:
  name: fio-job
spec:
  parallelism: 2
  completions: 2
  template:
    metadata:
      name: fio-pod
    spec:
      hostNetwork: true
      volumes:
       - name: fio-pv-volume
         persistentVolumeClaim:
          claimName: fio-pv-claim
      containers:
        - name: fio-test
          env:
            - name: CI
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: docker.io/pierreozoux/fio:latest
          args:
            - '--output-format=json'
            - '--blocksize=64k'
            - '--ioengine=libaio'
            - '--size=10G'
            - '--name=test'
            - '--direct=1'
            - '--iodepth=128'
            - '--filename=/mnt/fio.dat'
            - '--readwrite=write'
            - '--end_fsync=1'
          volumeMounts:
            - mountPath: "/data"
              name: fio-pv-volume
      restartPolicy: OnFailure

