apiVersion: batch/v1
kind: Job
metadata:
  name: {{FIO_JOB}}
spec:
  backoffLimit: 6
  completions: {{NUM_CLIENTS}}
  parallelism: {{NUM_CLIENTS}}
  template:
    metadata:
      name: fio-pod
    spec:
      containers:
      - args:
        - /fio_jobfiles/run_fio.sh
        command:
        - /bin/sh
        env:
        - name: FIO_RW
          value: "{{FIO_RW}}"
        - name: NUM_JOBS
          value: "{{NUM_JOBS}}"
        - name: NUM_CLIENTS
          value: "{{NUM_CLIENTS}}"
        - name: FIO_JOB
          value: "{{FIO_JOB}}"
        - name: SUB_JOB
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: docker.io/{{DOCKER_ID}}/fio:{{DOCKER_TAG}}
        imagePullPolicy: Always
        name: fio-test
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: fio-pv
        - mountPath: /results
          name: results-pv
          subPath: {{RESULT_SUBPATH}}
      hostNetwork: true
      restartPolicy: Never
      volumes:
      - name: data-pv
        hostPath:
          path: {{DATA_HOSTPATH}}
      - name: result-pv
        persistentVolumeClaim:
          claimName: manila-cephfs-pvc
